spring.application.name=ms-productos
sever.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://ep-snowy-morning-apnyhsqc-pooler.c-7.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_io1LjnhTz9wl&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_io1LjnhTz9wl&ssl
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jp.database-platform=org.hibernate.dialect.PostgreSQLDialect
